# Generated by Django 3.2.8 on 2021-10-11 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='first_name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='creator',
            name='last_name',
            field=models.CharField(max_length=25),
        ),
        migrations.CreateModel(
            name='Frameworks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('dil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relationships.language')),
            ],
        ),
    ]
